# Generated by Django 5.2.7 on 2025-10-14 12:52

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated.')),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the object this comment is attached to.')),
                ('content', models.TextField(help_text='Write the content of your comment here.')),
                ('author', models.ForeignKey(help_text='Select the user who is posting this comment.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(help_text='The type of object this comment is attached to (Question, Answer, or Comment).', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, help_text='If this is a reply, select the parent comment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated.')),
                ('title', models.CharField(help_text='Enter a concise title for your question (max 255 characters).', max_length=255)),
                ('description', models.TextField(help_text='Provide a detailed explanation of your question.')),
                ('author', models.ForeignKey(help_text='Select the user who is posting this question.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='Add relevant tags to categorize and improve discoverability of your question.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated.')),
                ('content', models.TextField(help_text='Write your answer here.')),
                ('author', models.ForeignKey(help_text='Select the user who is posting this answer.', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(help_text='The question this answer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forum.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the object was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the object was last updated.')),
                ('vote_type', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')], help_text="Choose 'Upvote' for +1 or 'Downvote' for -1.")),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the object being voted on.')),
                ('content_type', models.ForeignKey(help_text='The type of object being voted on (Question, Answer, or Comment).', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='Select the user who is casting this vote.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
